version: 2.1
description: # This is a CircleCi orb for Alexa skills


jobs:
  deploy_job:
    executor: default
    steps:
      - deploy_command
  install_job:
    executor: default
    steps:
      - install_command
  my_inline_job:
    parameters:
      greeting_name:
        description: # a helpful description
        type: string
        default: olleh
    executor: my_inline_executor
    steps:
      - my_inline_command:
          greeting_name: <<parameters.greeting_name>>
commands:
  install_command:
    steps:
      - run: sudo npm i -g ask-cli
      - run: ask -v
      - run: ask api list-skills
  my_inline_command:
    parameters:
      greeting_name:
        type: string
    steps:
      - run: echo "hello <<parameters.greeting_name>>, from the inline command"
  deploy_command:
    description: |
      Deploys an Alexa skill into development stage
    parameters:
      stage_name:
        type: string
        default: "development"
    steps:
      - run: ask deploy
  diff_command:
    description: |
      Takes a diff of your local version and the version on the server.
    steps:
      - run:
          command: ask diff
          name: Ask Diff.
executors:
  my_inline_executor:
    parameters:
      version:
        type: string
        default: "2.4"
    docker:
      - image: circleci/ruby:<<parameters.version>>
  default:
    description: |
      Node 10 runtime environment
    docker:
      - image: circleci/node:<<parameters.node>>
    parameters:
      node:
        default: "10"
        type: string

examples:
  deploy-my-skill:
    description: |
      Deploys an example Alexa skill to Alexa developer console in development stage.
    usage:
      orbs:
        alexa: alexa/alexa@0.0.2
      version: 2.1
      workflows:
        push:
          jobs:
            - alexa/diff
            - alexa/deploy