version: 2.1
description: # This is a CircleCi orb for Alexa skills, Please note that you need to set-up all the required environment values before being able to run the job! those include the AWS credentials and ASK credentials/tokens as described in this article: https://medium.com/p/21d8b3f3d737


jobs:
  deploy_job:
    executor: default
    parameters:
      is_forced:
        description: # If true a deployment will be forced even if the local and remote code bases have conflicting versions
        type: boolean
        default: false
    steps:
      - deploy_command
  install_job:
    executor: default
    steps:
      - install_command
commands:
  install_command:
    steps:
      - run: sudo npm i -g ask-cli
      - run: ask -v
      - run: ask api list-skills
  deploy_command:
    description: |
      Deploys an Alexa skill into development stage
    parameters:
      is_forced:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.is_forced >>
          steps:
            - run:
                ask deploy --force
      - unless:
          condition: << parameters.is_forced >>
          steps:
            - run:
                ask deploy
  diff_command:
    description: |
      Takes a diff of your local version and the version on the server.
    steps:
      - run:
          command: ask diff
          name: Ask Diff.
executors:
  default:
    description: |
      Node 10 runtime environment
    docker:
      - image: circleci/node:<<parameters.node>>
    parameters:
      node:
        default: "10"
        type: string

examples:
  deploy-my-skill:
    description: |
      Deploys an example Alexa skill to Alexa developer console in development stage.
    usage:
      orbs:
        alexa: alexa/alexa@0.0.3
      version: 2.1
      workflows:
        push:
          jobs:
            - alexa/diff
            - alexa/deploy